version: "1.0"

services:
  postgres:
    image: postgres:16-alpine3.18
    environment:
      POSTGRES_DB: "netologySam"
      POSTGRES_USER: "userSam"
      POSTGRES_PASSWORD: "password"
    ports:
      - 5432:5432